### ISSUE TITLE
Complete a Team Section 

### ISSUE THREAD

**Issue by ayushnandanwar** [ayushnandanwar08/ecell-website#3]
Hi participants,
here you need do some work on the website
- Create section using id=event
- Design as section as per given in theme
- you can make you use of any images ( you can add it to folder)

**Comment by AkashKMathew** [comment]
@ayushnandanwar08  I would like to work on this. Please assign to me.

**Comment by AkashKMathew** [comment]
In this website there is already a section with id=events. So do I need to edit it or create a new section with id=event? @ayushnandanwar08

**Comment by ayushnandanwar** [comment]
You can go with team section. I think it has not done.

**Comment by codesmith25103** [comment]
can you assign me this issue?

**Comment by ayushnandanwar** [comment]
Sure @codesmith25103 , Go ahead
Good luck

**Comment by ayushnandanwar** [comment]
Good Work @AkashKMathew
